#!/bin/bash
#https://www.boluscalculators.com
#info [at] boluscalculators dot com
#2021

#main menu script; choose your preference

echo "If preference is running the simulator with a rounding module, choose option 1, select $DEVICE, and select rounding module"
echo "If preference is not to apply rounding to the simulator's calculations, choose option 2, and select $DEVICE"
echo ''
read PREFERENCE
echo "$PREFERENCE" > PREFERENCE.txt

DEVICE_SELECTION=1

if [[ $PREFERENCE -eq 1 ]] && [[ $DEVICE_SELECTION -eq 1 ]]; then bash bolus-sim-device1; fi

if [[ $PREFERENCE -eq 2 ]] && [[ $DEVICE_SELECTION -eq 1 ]]; then bash bolus-sim-device1-test; fi

echo 'test'
rm PREFERENCE.txt
echo 'done'


#V
