#!/bin/bash
#
#https://www.boluscalculators.com
#info [at] boluscalculators dot com
#2021
#
#main menu script; choose your preference

echo "If preference is running the simulator with a rounding module, choose option 1, select $DEVICE, and select rounding module"
echo "If preference is not to apply rounding to the simulator's calculations, choose option 2, and select $DEVICE"
echo ''
read PREFERENCE
echo "$PREFERENCE" > PREFERENCE.txt

DEVICE_SELECTION=1

if [[ $DEVICE_SELECTION -eq 1 ]] && [[ $PREFERENCE -eq 1 ]]; then bash bolus-sim-device1; fi
if [[ $DEVICE_SELECTION -eq 2 ]] && [[ $PREFERENCE -eq 1 ]]; then bash bolus-sim-device2; fi
if [[ $DEVICE_SELECTION -eq 3 ]] && [[ $PREFERENCE -eq 1 ]]; then bash bolus-sim-device3; fi
if [[ $DEVICE_SELECTION -eq 4 ]] && [[ $PREFERENCE -eq 1 ]]; then bash bolus-sim-device4; fi
if [[ $DEVICE_SELECTION -eq 5 ]] && [[ $PREFERENCE -eq 1 ]]; then bash bolus-sim-device5; fi
if [[ $DEVICE_SELECTION -eq 6 ]] && [[ $PREFERENCE -eq 1 ]]; then bash bolus-sim-device6; fi
if [[ $DEVICE_SELECTION -eq 7 ]] && [[ $PREFERENCE -eq 1 ]]; then bash bolus-sim-device7; fi
if [[ $DEVICE_SELECTION -eq 8 ]] && [[ $PREFERENCE -eq 1 ]]; then bash bolus-sim-device8; fi
if [[ $DEVICE_SELECTION -eq 9 ]] && [[ $PREFERENCE -eq 1 ]]; then bash bolus-sim-device9; fi
if [[ $DEVICE_SELECTION -eq 10 ]] && [[ $PREFERENCE -eq 1 ]]; then bash bolus-sim-device10; fi

if [[ $DEVICE_SELECTION -eq 1 ]] && [[ $PREFERENCE -eq 2 ]]; then bash bolus-sim-device1-calc; fi
if [[ $DEVICE_SELECTION -eq 2 ]] && [[ $PREFERENCE -eq 2 ]]; then bash bolus-sim-device2-calc; fi
if [[ $DEVICE_SELECTION -eq 3 ]] && [[ $PREFERENCE -eq 2 ]]; then bash bolus-sim-device3-calc; fi
if [[ $DEVICE_SELECTION -eq 4 ]] && [[ $PREFERENCE -eq 2 ]]; then bash bolus-sim-device4-calc; fi
if [[ $DEVICE_SELECTION -eq 5 ]] && [[ $PREFERENCE -eq 2 ]]; then bash bolus-sim-device5-calc; fi
if [[ $DEVICE_SELECTION -eq 6 ]] && [[ $PREFERENCE -eq 2 ]]; then bash bolus-sim-device6-calc; fi
if [[ $DEVICE_SELECTION -eq 7 ]] && [[ $PREFERENCE -eq 2 ]]; then bash bolus-sim-device7-calc; fi
if [[ $DEVICE_SELECTION -eq 8 ]] && [[ $PREFERENCE -eq 2 ]]; then bash bolus-sim-device8-calc; fi
if [[ $DEVICE_SELECTION -eq 9 ]] && [[ $PREFERENCE -eq 2 ]]; then bash bolus-sim-device9-calc; fi
if [[ $DEVICE_SELECTION -eq 10 ]] && [[ $PREFERENCE -eq 2]]; then bash bolus-sim-device10-calc; fi
if [[ $DEVICE_SELECTION -eq 10 ]] && [[ $PREFERENCE -eq 2]]; then bash bolus-sim-device10-calc; fi
if [[ $DEVICE_SELECTION -eq 10 ]] && [[ $PREFERENCE -eq 2]]; then bash bolus-sim-device10-calc; fi

echo 'test'
rm PREFERENCE.txt
echo 'done'


#V
